//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exception {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceErrorMessages___Copy
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceErrorMessages___Copy()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Exception.ResourceErrorMessages - Copy", typeof(ResourceErrorMessages___Copy).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Amount must be greater than zero..
        /// </summary>
        public static string AMOUNT_MUST_BE_GREATER_THAN_ZERO
        {
            get
            {
                return ResourceManager.GetString("AMOUNT_MUST_BE_GREATER_THAN_ZERO", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error messages cannot be null..
        /// </summary>
        public static string ERROR_CANNOT_BE_NULL
        {
            get
            {
                return ResourceManager.GetString("ERROR_CANNOT_BE_NULL", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Date cannot be in the future..
        /// </summary>
        public static string EXPENSES_CANNOT_FOR_THE_FUTURE
        {
            get
            {
                return ResourceManager.GetString("EXPENSES_CANNOT_FOR_THE_FUTURE", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid payment method..
        /// </summary>
        public static string INVALID_PAYMENT_METHOD
        {
            get
            {
                return ResourceManager.GetString("INVALID_PAYMENT_METHOD", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Payment method cannot be empty or null..
        /// </summary>
        public static string PAYMENT_METHOD_CANNOT_BE_NULL
        {
            get
            {
                return ResourceManager.GetString("PAYMENT_METHOD_CANNOT_BE_NULL", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Title cannot be empty or null..
        /// </summary>
        public static string TITLE_REQUIRED
        {
            get
            {
                return ResourceManager.GetString("TITLE_REQUIRED", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to An unknown error occurred..
        /// </summary>
        public static string UNKNOWN_ERROR
        {
            get
            {
                return ResourceManager.GetString("UNKNOWN_ERROR", resourceCulture);
            }
        }

        public static string ID_MUST_BE_GREATER_THAN_ZERO
        {
            get {
                return ResourceManager.GetString("ID_MUST_BE_GREATER_THAN_ZERO", resourceCulture);
            }
        }
    }
}
